# args: location, pack_item_ls

# a location is a dictionary item that includes:
#   number of storage spaces,
#   array of storage space dims,
#   type of package storage space accepts
#   location of storage facility

# e.g. { 3, [(5,5,5),(5,5,5),(5,5,5)], [('Custom Crate', 'Cardboard Box', 'Taco Shell')], altanta }

# a pack_item_ls is generated by the pack.py file
# it is a dictionary containing all pack items and their information

# a pack_item_ls is a dictionary item that includes:
#   ~ see pack.py for the dict item structure

# returns: dictionary of all the items that will fit best into each approritate 
# storage location


# dev env

import pack

i = pack.item_ls('../DATA/jan_pack.xlsx')
dic = i.ls_xml()

# end dev env

# actual dependecies
from utils import append_pack_info



location = {}
location['location 1'] = ( 3, [(96,48,60),(96,48,60),(48,48,60)], [['Custom Crate', 'Cardboard Box', 'Taco Shell', 'Slipcase', 'slipcase', 'Tube'], ['Tube', 'Custom Crate', 'Cardboard Box'], ['Taco Shell', 'slipcase'] ], 'Big Blue' )


class storage_spaces():

    def __init__(self, location, pack_item_ls):

        self.location = location
        self.pack_item_ls = pack_item_ls
    

    # check to make sure the packages are all supposed to be going to the same place
    def in_right_location(self):

        right_location = {}
        wrong_location = {} #TODO send wrong_locatoin somewhere

        storage_facility = self.location['location 1'][3]
        
        for k, v in self.pack_item_ls.items():
            if v[6] == storage_facility:
                #print(k + 'is in the right location')
                item = list(v)
                item2 = append_pack_info(item, self.location['location 1'][2])
                right_location[k] = item2
            else:
                #print(k +' is in ' + v[6] + ' instead of in ' + storage_facility)
                wrong_location[k] = v

        return right_location

    # split the packages by packing type
    def pack_types_in_spaces(self):

        # upgraded self.pack_item_ls

        i = self.in_right_location() #TOBE removed

        # dic with each storage_space as key and values of all items that can be alloted to them
        # in terms of accepted packing materials

        storage_facility = self.location['location 1']
        for num in range(self.location['location 1'][0]):
            space_size = storage_facility[1][num]
            storage_spaces_allotment = storage_facility[2][num]
            print(space_size, storage_spaces_allotment)
            for k, v in i.items():
                pass



    #def pack_types():
    #    pass
    # assign packages to their correct location
    #def assign_location():
    #    pass

i = storage_spaces(location, dic)
dicks = i.pack_types_in_spaces()
print(dicks, 'i')
